### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by aciceri** [mh4x0f/zmkBATx#1]
Hey, cool project.

I wanted to write [nix](https://github.com/NixOS/nixpkgs) expressions for this but it's not clear to me how it's supposed to be built.

**Comment by mh4x0f** [comment]
I'm using qmake for build the project from Qt6.6.2:

``` sh
/home/mh4x0f/Qt/6.6.2/gcc_64/bin/qmake /home/mh4x0f/git/zmkBATx/zmkBATx.pro -spec linux-g++ CONFIG+=qtquickcompiler && /usr/bin/make qmake_all

make -j8 in /home/mh4x0f/git/zmkBATx
```

the qt requires somes libraries then you can get on release .tar.gz file.

**Comment by aciceri** [comment]
In general (modulo some workarounds) it's not possible running pre-built binaries in NixOS, and its philosophy is more about re-building everything from sources.
I've packaged it, [here the PR](https://github.com/NixOS/nixpkgs/pull/315844).

If you have nix installed you can already try to build it with nix (and then start it) using:
```bash
nix run github:aciceri/nixpkgs/zmkbatx#zmkBATx
```

If you want I can add a reference to the fact that it's packged in nipxkgs in the README (after the PR is merged).

It works great anyway!

**Comment by mh4x0f** [comment]
yeah, nice job brow. send me a PR after merge on nix package.
